version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0


workflows:
  default:
    jobs:
      - test
      
jobs:
  test:
    executor: base
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Gradle Clean & Compile
                command: |
                  ./retry_zinc ./gradlew -PscalaVersion=2.13 clean compileJava compileScala compileTestJava compileTestScala spotlessScalaCheck checkstyleMain checkstyleTest spotbugsMain rat --profile --no-daemon --continue -PxmlSpotBugsReport=true 
            - run:
                name: Gradle Unit & IT Tests
                command: |
                  ./gradlew -PscalaVersion=2.12 unitTest integrationTest --profile --no-daemon --continue -PtestLoggingEvents=started,passed,skipped,failed -PignoreFailures=true -PmaxParallelForks=20 -PmaxTestRetries=1 -PmaxTestRetryFailures=10 || echo "Tests failed, but we want cache."
      - store_artifacts:
          path: /home/circleci/project/build/reports
      - store_test_results:
          path: /home/circleci/project/build/test-results/
executors:
  base:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: 2xlarge+

# VS Code Extension Version: 1.1.1