version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0


workflows:
  default:
    jobs:
      - test
      
jobs:
  test:
    executor: base
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Gradle Build
                command: ./retry_zinc ./gradlew -PscalaVersion=2.13 clean compileJava compileScala compileTestJava compileTestScala spotlessScalaCheck checkstyleMain checkstyleTest spotbugsMain rat --profile --no-daemon --continue -PxmlSpotBugsReport=true
      - store_artifacts:
          path: /home/circleci/project/build/reports
      - store_test_results:
          path: /home/circleci/project/build/reports/tests
executors:
  base:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: 2xlarge+

# VS Code Extension Version: 1.1.1